In [14]:
import numpy as np

## reshape

In [11]:
arr = np.array([[1,2,3],[4,5,6]])

In [9]:
print(arr.reshape(6,1))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [12]:
print(arr.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


In [16]:
print(arr.reshape(1,6))

[[1 2 3 4 5 6]]


## arange

In [19]:
print(np.arange(30))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [21]:
print(np.arange(0,10,3))

[0 3 6 9]


## reshape + arange

In [24]:
print(np.arange(1, 26).reshape(5,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [30]:
print(np.arange(0,6,0.2).reshape(3,2,5))

[[[0.  0.2 0.4 0.6 0.8]
  [1.  1.2 1.4 1.6 1.8]]

 [[2.  2.2 2.4 2.6 2.8]
  [3.  3.2 3.4 3.6 3.8]]

 [[4.  4.2 4.4 4.6 4.8]
  [5.  5.2 5.4 5.6 5.8]]]


## zeros         np((shape,dtype)

In [34]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [36]:
np.zeros((5,1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [46]:
np.zeros((2,3),dtype = int)

array([[0, 0, 0],
       [0, 0, 0]])

## ones

In [49]:
np.ones((2,5),dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## empty

In [51]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

## zeros_like  
## ones_like  
## empty_like

In [66]:
arr = np.arange(24).reshape(4,6)
arr.dtype

dtype('int32')

In [73]:
np.zeros_like(arr)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [75]:
arr = np.arange(-2,2,0.2).reshape(2,10)
arr.dtype

dtype('float64')

In [78]:
np.ones_like(arr)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [79]:
np.empty_like(arr)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## identity

In [81]:
np.identity((5),dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [83]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

## eye(size, m, k, dtype)
# k : 대각선의 시작 위치를 입력 받은 수 만큼 오른쪽으로 이동
# m : 보여지는 열의 개수 지정

In [87]:
np.eye((5),dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [99]:
np.eye(5, M = 8, k = -1)

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.]])

## full 

In [102]:
np.full((3,2,5),5)

array([[[5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5]],

       [[5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5]],

       [[5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5]]])

## random.randint

In [233]:
# 0 ~ 5
np.random.randint(6)

5

In [393]:
# 1 ~ 19
np.random.randint(1,20,size = 2)
np.random.randint(1,20,2)

array([14, 14])

In [530]:
np.random.randint(1,10,10)

(1, 10, 10)

## random.rand

In [532]:
## 0 ~ 1 값
np.random.rand(3,2)

array([[0.98666513, 0.81495843],
       [0.31332657, 0.49155235],
       [0.78496244, 0.54899225]])

## random.randn

In [535]:
# 평균 0 표준편자 1
np.random.randn(3,2)

array([[ 0.23017664, -0.946901  ],
       [-0.90743051, -0.58651239],
       [ 0.92268882,  0.25891617]])

## 연산

In [552]:
# sum
arr = np.random.randn(5,2)
arr

array([[-0.06117983,  1.0988409 ],
       [-0.40259999,  0.21805393],
       [-1.13389541, -0.12901068],
       [ 0.86763911,  0.17598246],
       [ 0.17468309,  1.21801347]])

In [548]:
sum(arr)

array([-3.9256439 ,  2.95944096])

In [556]:
arr.sum(axis=0) # 위 아래

array([-0.55535303,  2.58188008])

In [555]:
arr.sum(axis=1) # 좌우

array([ 1.03766106, -0.18454605, -1.2629061 ,  1.04362157,  1.39269656])

In [553]:
# mean
arr.mean()

0.2026527046524922

In [558]:
# std
arr.std()

0.6789954617564196

In [560]:
arr.std(axis=0) # 위 아래

array([0.65926883, 0.53906368])

In [561]:
arr.std(axis=1) # 좌우

array([0.58001036, 0.31032696, 0.50244237, 0.34582832, 0.52166519])

## sort 배열 정렬

In [ ]:
[ np.random.randint(1,101) for n in range(5)  ]

In [570]:
np.random.randint(1,101)

67

In [577]:
[ i if i % 2 ==0 else 0 for i in range(5)]

[0, 0, 2, 0, 4]

In [615]:
vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])

np.vstack([vector1, vector1])  # 수직 합체

array([[1, 2, 3],
       [1, 2, 3]])

In [584]:
vector1 = np.array([1,2,3]).reshape(3,1)
vector2 = np.array([4,5,6]).reshape(3,1)

np.hstack([vector1,vector2])  # 수평 합체

array([[1, 4],
       [2, 5],
       [3, 6]])

In [594]:
vector1 = np.array([1,2,3]).reshape(3,1)
vector2 = np.array([4,5,6]).reshape(3,1)

np.concatenate([vector1,vector2],axis=0)   #0: 수직   1: 수평

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [595]:
matrix = np.array([[1,2,3],[4,5,6]])
vector = np.array([7,8,9])

In [616]:
np.vstack([matrix,vector])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 행/열 바꾸기 (transpose)

In [632]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [633]:
matrix.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [637]:
np.concatenate([matrix.T],axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

## argmax, agrmin

In [641]:
arr = np.arange(1,11).reshape(2,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [648]:
np.argmin(arr),np.argmax(arr)  # 인덱스 값

(0, 9)

## fancy index

In [658]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [662]:
b = np.argmax(a)

In [663]:
print(a[b])

10
